name: Test aiohttp

on:
  push:
    branches:
      - master
      - release/**

  pull_request:

permissions:
  contents: read

env:
  BUILD_CACHE_KEY: ${{ github.sha }}
  CACHED_BUILD_PATHS: |
    ${{ github.workspace }}/dist-serverless

jobs:
  test:
    name: aiohttp ${{ matrix.aiohttp-version }}, python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7"]
        aiohttp-version: ["3.5"]
        include:    
          - { aiohttp-version: "3.5", python-version: "3.7", os: "ubuntu-latest" }
          - { aiohttp-version: "3.6", python-version: "3.7", os: "ubuntu-latest" }
          - { aiohttp-version: "3.6", python-version: "3.8", os: "ubuntu-latest" }
          - { aiohttp-version: "3.6", python-version: "3.9", os: "ubuntu-latest" }
          - { aiohttp-version: "3.6", python-version: "3.10", os: "ubuntu-latest" }

    steps:
      - uses: actions/checkout@v3
      #- uses: actions/setup-node@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Test Env
        env:
          PGHOST: localhost
          PGPASSWORD: sentry
        run: |
          pip install codecov tox

      - name: Test aiohttp
        env:
          CI_PYTHON_VERSION: ${{ matrix.python-version }}
        timeout-minutes: 45
        shell: bash
        run: |
          set -x # print commands that are executed
          coverage erase

          envname=$(python ./scripts/tox_env_name.py ${{ matrix.python-version }} aiohttp ${{ matrix.aiohttp-version }})
          ./scripts/runtox.sh "$envname" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
          coverage combine .coverage*
          coverage xml -i
          codecov --file coverage.xml