name: Test GraphQL
on:
  push:
    branches:
      - master
      - release/**
      - sentry-sdk-2.0
  pull_request:
# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
env:
  BUILD_CACHE_KEY: ${{ github.sha }}
  CACHED_BUILD_PATHS: |
    ${{ github.workspace }}/dist-serverless
jobs:
  test-graphql-latest:
    name: GraphQL (latest)
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.8","3.11","3.12"]
        # python3.6 reached EOL and is no longer being supported on
        # new versions of hosted runners on Github Actions
        # ubuntu-20.04 is the last version that supported python3.6
        # see https://github.com/actions/setup-python/issues/544#issuecomment-1332535877
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Test Env
        run: |
          pip install coverage tox
      - name: Erase coverage
        run: |
          coverage erase
      - name: Test ariadne latest
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh "py${{ matrix.python-version }}-ariadne-latest" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test gql latest
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh "py${{ matrix.python-version }}-gql-latest" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test graphene latest
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh "py${{ matrix.python-version }}-graphene-latest" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test strawberry latest
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh "py${{ matrix.python-version }}-strawberry-latest" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Generate coverage XML
        run: |
          coverage combine .coverage*
          coverage xml -i
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
  test-graphql-pinned:
    name: GraphQL (pinned)
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.8","3.11","3.12"]
        # python3.6 reached EOL and is no longer being supported on
        # new versions of hosted runners on Github Actions
        # ubuntu-20.04 is the last version that supported python3.6
        # see https://github.com/actions/setup-python/issues/544#issuecomment-1332535877
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Test Env
        run: |
          pip install coverage tox
      - name: Erase coverage
        run: |
          coverage erase
      - name: Test ariadne pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-ariadne" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test gql pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-gql" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test graphene pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-graphene" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test strawberry pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-strawberry" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Generate coverage XML
        run: |
          coverage combine .coverage*
          coverage xml -i
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
  check_required_tests:
    name: All GraphQL tests passed
    needs: test-graphql-pinned
    # Always run this, even if a dependent job failed
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - name: Check for failures
        if: contains(needs.test-graphql-pinned.result, 'failure') || contains(needs.test-graphql-pinned.result, 'skipped')
        run: |
          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
