name: Test Web Frameworks 2
on:
  push:
    branches:
      - master
      - release/**
      - 1.x
  pull_request:
# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
env:
  BUILD_CACHE_KEY: ${{ github.sha }}
  CACHED_BUILD_PATHS: |
    ${{ github.workspace }}/dist-serverless
jobs:
  test-web_frameworks_2-pinned:
    name: Web Frameworks 2 (pinned)
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.5","3.6","3.7","3.8","3.9","3.11","3.12"]
        # python3.6 reached EOL and is no longer being supported on
        # new versions of hosted runners on Github Actions
        # ubuntu-20.04 is the last version that supported python3.6
        # see https://github.com/actions/setup-python/issues/544#issuecomment-1332535877
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Test Env
        run: |
          pip install coverage "tox>=3,<4"
      - name: Erase coverage
        run: |
          coverage erase
      - name: Test aiohttp pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-aiohttp" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test asgi pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-asgi" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test bottle pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-bottle" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test falcon pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-falcon" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test pyramid pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-pyramid" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test quart pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-quart" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test sanic pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-sanic" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test starlite pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-starlite" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test tornado pinned
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py${{ matrix.python-version }}-tornado" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Generate coverage XML
        run: |
          coverage combine .coverage*
          coverage xml -i
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
  test-web_frameworks_2-py27:
    name: Web Frameworks 2 (py27)
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    container: python:2.7
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Test Env
        run: |
          pip install coverage "tox>=3,<4"
      - name: Erase coverage
        run: |
          coverage erase
      - name: Test aiohttp py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-aiohttp" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test asgi py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-asgi" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test bottle py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-bottle" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test falcon py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-falcon" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test pyramid py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-pyramid" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test quart py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-quart" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test sanic py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-sanic" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test starlite py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-starlite" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Test tornado py27
        run: |
          set -x # print commands that are executed
          ./scripts/runtox.sh --exclude-latest "py2.7-tornado" --cov=tests --cov=sentry_sdk --cov-report= --cov-branch
      - name: Generate coverage XML
        run: |
          coverage combine .coverage*
          coverage xml -i
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
  check_required_tests:
    name: All Web Frameworks 2 tests passed
    needs: [test-web_frameworks_2-pinned, test-web_frameworks_2-py27]
    # Always run this, even if a dependent job failed
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - name: Check for failures
        if: contains(needs.test-web_frameworks_2-pinned.result, 'failure') || contains(needs.test-web_frameworks_2-pinned.result, 'skipped')
        run: |
          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
      - name: Check for 2.7 failures
        if: contains(needs.test-web_frameworks_2-py27.result, 'failure') || contains(needs.test-web_frameworks_2-py27.result, 'skipped')
        run: |
          echo "One of the dependent jobs has failed. You may need to re-run it." && exit 1
